// This file is generated by digogen. Run 'digogen' to regenerate.
//
// You can install this tool by running `go install github.com/werbenhu/digo/digogen`.
// For more details, please refer to https://github.com/werbenhu/digo.
package models

import (
	"github.com/werbenhu/digo"
	"github.com/werbenhu/digo/examples/multipackage/database"
)

// init_model_user registers the singleton object with ID model.user into the DI object manager
// Now you can retrieve the singleton object by using `obj, err := digo.Provide("model.user")`.
// The obj obtained from the above code is of type `any`.
// You will need to forcefully cast the obj to its corresponding actual object type.
func init_model_user() {
	db_obj, err := digo.Provide("database.mysql")
	if err != nil {
		panic(err)
	}
	db := db_obj.(database.Database)
	model_user_obj := NewUser(db)
	digo.RegisterSingleton("model.user", model_user_obj)
}

// init registers all providers in the current package into the DI object manager.
func init() {
	init_model_user()
}
